### ISSUE TITLE
Should we support asyncio?

### ISSUE THREAD

**Issue by vogt4nick** [vogt4nick/dequindre#75]
`asyncio` comes standard in python 3.5 and later.

**Comment by josecolella** [comment]
@vogt4nick for IO tasks I definitely recommend it.

**Comment by vogt4nick** [comment]
@josecolella it could be extremely valuable to speed up workflows. I'll research the `asyncio` and `threading` libraries. I'll look into `multithreading` too, but parallel tasks can throw funny exceptions if you don't know what's happening under the hood. 

I'm checking boxes in my head that look like this:

- [ ] Minimal abstraction
- [x] No Python dependencies; no third-party bugs
- [x] Single-container deployment
- [ ] Legible source code; fewer than 1000 lines
- [x] Fast, dynamic workflow configuration

I'll be hesitant to add it unless I can check all the boxes.

**Comment by josecolella** [comment]
For multhreading libraries remember that the GIL is always something that will restrict you from achieving true multi threading. If the problem is IO bound, asyncio is definitely the way to go. :)

**Comment by vogt4nick** [comment]
I'm convinced we should support asynchronous tasks. That will be the most immediate need in upcoming versions.
